language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh --quiet verify
deploy:
  - provider: script
script: ./deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
  skip_cleanup: true
  on:
   tags: true
