apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shop-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: best-shop-local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: shop-ui
          servicePort: 80