apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-api
    env: dev
    ver: v1
  name: 'shop'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: shop-api