apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
        env: dev
        ver: v1
    spec:
      containers:
        - image: 'postgres:9.6.2'
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value:
            - name: PGDATA
              value: /var/lib/postgresql/data/share
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
          - name: nfs
            mountPath: /var/lib/postgresql/data/share
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfsslow
          
          